[theme]
primaryColor = "#0A2342"
backgroundColor = "#F5F5F5"
secondaryBackgroundColor = "#FFFFFF"
textColor = "#0A2342"
font = "sans serif"

[server]
maxUploadSize = 200
enableCORS = true
enableXsrfProtection = true
runOnSave = true
# Add module reloading to ensure all modules are properly loaded
enableWebsocketCompression = true

[browser]
gatherUsageStats = false
